# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_native', models.CharField(max_length=100)),
                ('abrv', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('cdf_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'metadata"."institutions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=100)),
                ('tspr', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('dts', models.CharField(max_length=100)),
                ('dte', models.CharField(max_length=100)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('params', models.CharField(max_length=100)),
                ('platform_code', models.CharField(max_length=100)),
                ('wmo', models.CharField(max_length=100)),
                ('pi_name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('island', models.BooleanField()),
                ('pl_name', models.CharField(max_length=100)),
                ('inst_ref', models.CharField(max_length=100)),
                ('assembly_center', models.CharField(max_length=100)),
                ('site_code', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'metadata"."platforms',
                'managed': False,
            },
        ),
    ]
