# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_institution_platform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='platform',
            options={'managed': False, 'verbose_name_plural': 'platforms'},
        ),
    ]
