# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180227_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('posqc', models.SmallIntegerField(blank=True, default='0', null=True)),
                ('pres', models.FloatField(blank=True, null=True)),
                ('presqc', models.SmallIntegerField(blank=True, default='0', null=True)),
                ('val', models.FloatField(blank=True, null=True)),
                ('valqc', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'data',
                'db_table': 'pr_pf_6900795_all_data_mv',
                'managed': False,
            },
        ),
    ]
