# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-27 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('long_name', models.CharField(max_length=100)),
                ('stand_name', models.CharField(max_length=100)),
                ('fval_qc', models.ImageField(upload_to='')),
                ('fval', models.FloatField(blank=True, null=True)),
                ('category_long', models.CharField(max_length=100)),
                ('category_short', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'metadata"."parameters',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'managed': False, 'ordering': ('-id',), 'verbose_name_plural': 'data'},
        ),
        migrations.AlterModelTable(
            name='test',
            table='data"."PR_PF_6900795',
        ),
    ]
