# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-26 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180319_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ferrybox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('posqc', models.SmallIntegerField(blank=True, default='0', null=True)),
                ('pres', models.FloatField(blank=True, null=True)),
                ('presqc', models.SmallIntegerField(blank=True, default='0', null=True)),
                ('val', models.FloatField(blank=True, null=True)),
                ('valqc', models.SmallIntegerField(blank=True, default='0', null=True)),
                ('dvalqc', models.SmallIntegerField(blank=True, null=True)),
                ('route_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Ferrybox',
                'db_table': 'data"."TS_FB_SAEG01',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
