# Generated by Django 2.0.5 on 2018-05-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ferrybox'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.TextField()),
                ('querystring', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Request',
                'db_table': 'uman"."requests',
                'ordering': ('-id',),
                'managed': False,
            },
        ),
    ]
