# Generated by Django 2.0.5 on 2018-05-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cdf_Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'metadata"."cdf_institutions',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
