# Generated by Django 2.0.5 on 2018-06-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.CharField(default='Nothing', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
