# Generated by Django 2.0.5 on 2018-08-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180711_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.TextField()),
                ('dt', models.DateTimeField(blank=True, null=True)),
                ('param', models.SmallIntegerField(blank=True, default='0', null=True)),
                ('val', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'OnlineData',
                'db_table': 'public"."hcmr_online_data',
                'ordering': ('id',),
                'managed': False,
            },
        ),
    ]
