# Generated by Django 2.0.5 on 2018-08-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180801_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onlinedata',
            options={'managed': False, 'verbose_name_plural': 'OnlineData'},
        ),
    ]
